sudo: required
services:
  - docker

before_install:
  - docker build -t manish160993/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true manish160993/react-test npm test

after_success:
  - docker build -t manish160993/multi-client ./client
  - docker build -t manish160993/multi-nginx ./nginx
  - docker build -t manish160993/multi-server ./server
  - docker build -t manish160993/multi-worker ./worker
  #Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push manish160993/multi-client
  - docker push manish160993/multi-nginx
  - docker push manish160993/multi-server
  - docker push manish160993/multi-worker